# Generated by Django 6.0.8 on 2026-09-02 08:01

import django.db.models.deletion
import liveclassroom.models.session
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('true_false', 'True / false'), ('poll', 'Poll'), ('short_text', 'Short text')], max_length=32)),
                ('stem_markdown', models.TextField()),
                ('data', models.JSONField(default=dict, help_text='Versioned display definition, such as choices.')),
                ('answer', models.JSONField(blank=True, default=list)),
                ('explanation_markdown', models.TextField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='liveclassroom.course')),
            ],
            options={
                'ordering': ['course', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FlowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('markdown', 'Markdown'), ('question', 'Question'), ('poll', 'Poll'), ('image', 'Image'), ('video', 'Video'), ('url', 'URL'), ('iframe', 'IFrame'), ('timer', 'Timer')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liveclassroom.flow')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_items', to='liveclassroom.question')),
            ],
            options={
                'ordering': ['flow', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(default=liveclassroom.models.session.make_join_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting', 'Waiting'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=16)),
                ('mode', models.CharField(choices=[('teacher_paced', 'Teacher paced'), ('student_paced', 'Student paced'), ('exam', 'Exam')], default='teacher_paced', max_length=20)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='liveclassroom.course')),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_sessions', to='liveclassroom.flowitem')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='liveclassroom.flow')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_sessions_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=16)),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('revealed', 'Revealed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_activities', to='liveclassroom.flowitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('assistant', 'Assistant'), ('student', 'Student')], default='student', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='liveclassroom.livesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_events', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='liveclassroom.liveactivity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='liveclassroom.participant')),
            ],
            options={
                'ordering': ['activity', 'participant', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('assistant', 'Assistant'), ('student', 'Student')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='liveclassroom.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'user'],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='lc_membership_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='lc_flow_slug_per_course'),
        ),
        migrations.AddConstraint(
            model_name='liveactivity',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='lc_activity_sequence'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('session', 'user'), name='lc_one_user_participant_per_session'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id', ''), _negated=True), fields=('session', 'guest_id'), name='lc_one_guest_participant_per_session'),
        ),
        migrations.AddConstraint(
            model_name='flowitem',
            constraint=models.UniqueConstraint(fields=('flow', 'position'), name='lc_flow_item_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='lc_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('activity', 'participant', 'attempt'), name='lc_submission_attempt'),
        ),
    ]
