# Generated by Django 6.0.3 on 2026-09-04 05:16

import django.db.models.deletion
import liveclassroom.models.session
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=100)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('definition', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_activity_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityDefinitionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_activity_revisions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.activitydefinition')),
            ],
            options={
                'ordering': ['definition', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_definitions', to='liveclassroom.activitydefinitionrevision'),
        ),
        migrations.CreateModel(
            name='ActivityRunRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_activity_run_revisions', to=settings.AUTH_USER_MODEL)),
                ('source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_runs', to='liveclassroom.activitydefinitionrevision')),
            ],
            options={
                'ordering': ['activity', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringCommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=160)),
                ('command_type', models.CharField(max_length=80)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_authoring_command_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['owner', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('assistant', 'Assistant')], max_length=16)),
                ('content', models.TextField()),
                ('model_identifier', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_authoring_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('activity', 'Activity'), ('flow', 'Flow'), ('flow_step', 'Flow step'), ('provider', 'Content provider')], max_length=32)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('reference', models.JSONField(blank=True, default=dict)),
                ('source_fingerprint', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='liveclassroom.authoringmessage')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuthoringThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New authoring conversation', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_authoring_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='authoringmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='liveclassroom.authoringthread'),
        ),
        migrations.CreateModel(
            name='AuthoringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_key', models.CharField(max_length=100)),
                ('model_identifier', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=64)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_jobs_as_response', to='liveclassroom.authoringmessage')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='liveclassroom.authoringmessage')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='liveclassroom.authoringthread')),
            ],
            options={
                'ordering': ['-queued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_definitions', to='liveclassroom.course'),
        ),
        migrations.CreateModel(
            name='CourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('assistant', 'Assistant'), ('student', 'Student')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='liveclassroom.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='liveclassroom.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_flows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['course', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_steps', to='liveclassroom.activitydefinition')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='liveclassroom.flow')),
            ],
            options={
                'ordering': ['flow', 'position'],
            },
        ),
        migrations.CreateModel(
            name='LiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(max_length=16)),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('reviewable', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('revealed', 'Revealed')], default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_activities', to='liveclassroom.activityrunrevision')),
                ('source_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_activities', to='liveclassroom.flowstep')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='activityrunrevision',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.liveactivity'),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Live classroom', max_length=200)),
                ('join_code', models.CharField(default=liveclassroom.models.session.make_join_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=16)),
                ('access_mode', models.CharField(choices=[('guest', 'Guest link'), ('authenticated', 'Authenticated users'), ('both', 'Guest link and authenticated users')], default='guest', max_length=20)),
                ('admission_mode', models.CharField(choices=[('open', 'Open'), ('waiting_room', 'Waiting room'), ('roster', 'Roster only')], default='open', max_length=20)),
                ('chat_enabled', models.BooleanField(default=False)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='liveclassroom.course')),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='liveclassroom.flow')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_sessions_hosted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='liveactivity',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='liveclassroom.livesession'),
        ),
        migrations.CreateModel(
            name='CommandReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=160)),
                ('command_type', models.CharField(max_length=80)),
                ('request_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_command_receipts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_receipts', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_id', models.CharField(blank=True, max_length=128)),
                ('display_name', models.CharField(max_length=100)),
                ('admission_state', models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='admitted', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='liveclassroom.livesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.CharField(max_length=255, unique=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='liveclassroom.participant')),
            ],
            options={
                'ordering': ['participant', 'connected_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionChannelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('display', 'Classroom display'), ('participants', 'Participants')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('show_prompt', models.BooleanField(default=True)),
                ('show_aggregate', models.BooleanField(default=False)),
                ('show_answer', models.BooleanField(default=False)),
                ('show_explanation', models.BooleanField(default=False)),
                ('show_own_status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_states', to='liveclassroom.liveactivity')),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_states', to='liveclassroom.activityrunrevision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_states', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_events', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='liveclassroom.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_messages', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='liveclassroom.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cohost', 'Co-host'), ('assistant', 'Assistant'), ('observer', 'Observer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='liveclassroom.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(default=dict)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_stale', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='liveclassroom.liveactivity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='liveclassroom.participant')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_submission_revisions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['activity', 'participant', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('answer', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_revisions', to='liveclassroom.activityrunrevision')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.submission')),
            ],
            options={
                'ordering': ['submission', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_submissions', to='liveclassroom.submissionrevision'),
        ),
        migrations.AddConstraint(
            model_name='activitydefinitionrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='lc_definition_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='authoringcommandreceipt',
            constraint=models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='lc_authoring_receipt_once'),
        ),
        migrations.AddIndex(
            model_name='authoringthread',
            index=models.Index(fields=['owner', 'updated_at'], name='liveclassro_owner_i_f7d772_idx'),
        ),
        migrations.AddIndex(
            model_name='authoringjob',
            index=models.Index(fields=['thread', 'status'], name='liveclassro_thread__1859db_idx'),
        ),
        migrations.AddIndex(
            model_name='authoringjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='liveclassro_status_4bac7a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitydefinition',
            index=models.Index(fields=['owner', 'type_key'], name='liveclassro_owner_i_1599fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemembership',
            constraint=models.UniqueConstraint(fields=('course', 'user'), name='lc_membership_once'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('course', 'slug'), name='lc_flow_slug_per_course'),
        ),
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(fields=('flow', 'position'), name='lc_flow_step_position'),
        ),
        migrations.AddConstraint(
            model_name='activityrunrevision',
            constraint=models.UniqueConstraint(fields=('activity', 'revision'), name='lc_activity_run_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='liveactivity',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='lc_activity_sequence'),
        ),
        migrations.AddConstraint(
            model_name='commandreceipt',
            constraint=models.UniqueConstraint(fields=('session', 'idempotency_key'), name='lc_command_receipt_once'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('session', 'user'), name='lc_one_user_participant_per_session'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id', ''), _negated=True), fields=('session', 'guest_id'), name='lc_one_guest_participant_per_session'),
        ),
        migrations.AddIndex(
            model_name='participantconnection',
            index=models.Index(fields=['participant', 'disconnected_at'], name='liveclassro_partici_19bd82_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionchannelstate',
            constraint=models.UniqueConstraint(fields=('session', 'channel'), name='lc_session_channel_once'),
        ),
        migrations.AddConstraint(
            model_name='sessionevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='lc_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='sessionstaff',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='lc_session_staff_once'),
        ),
        migrations.AddConstraint(
            model_name='submissionrevision',
            constraint=models.UniqueConstraint(fields=('submission', 'revision'), name='lc_submission_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('activity', 'participant', 'attempt'), name='lc_submission_attempt'),
        ),
    ]
