# Generated by Django 6.0.3 on 2026-09-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh-Hans', 'Simplified Chinese')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demo_lessons', to='liveclassroom.course')),
                ('ended_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_ended_for', to='liveclassroom.livesession')),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_lesson', to='liveclassroom.flow')),
                ('live_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_live_for', to='liveclassroom.livesession')),
                ('ready_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='demo_ready_for', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['slug', 'language'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='lc_demo_lesson_slug_language')],
            },
        ),
    ]
