# Generated by Django 6.0.3 on 2026-09-03 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_flows_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livesession',
            name='access_mode',
            field=models.CharField(choices=[('guest', 'Guest link'), ('authenticated', 'Authenticated users'), ('both', 'Guest link and authenticated users')], default='guest', max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='admission_mode',
            field=models.CharField(choices=[('open', 'Open'), ('waiting_room', 'Waiting room'), ('roster', 'Roster only')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='livesession',
            name='chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livesession',
            name='title',
            field=models.CharField(default='Live classroom', max_length=200),
        ),
        migrations.AddField(
            model_name='participant',
            name='admission_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('admitted', 'Admitted'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='admitted', max_length=16),
        ),
        migrations.AddField(
            model_name='participant',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_events', to='liveclassroom.participant'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_stale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flow',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='liveclassroom.course'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='liveclassroom.course'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='liveclassroom.flow'),
        ),
        migrations.CreateModel(
            name='ActivityDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_key', models.CharField(max_length=100)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('definition', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_definitions', to='liveclassroom.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_activity_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='flowitem',
            name='activity_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_flow_items', to='liveclassroom.activitydefinition'),
        ),
        migrations.CreateModel(
            name='ActivityDefinitionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('change_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_activity_revisions', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.activitydefinition')),
            ],
            options={
                'ordering': ['definition', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_definitions', to='liveclassroom.activitydefinitionrevision'),
        ),
        migrations.CreateModel(
            name='ActivityRunRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('definition_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.liveactivity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_activity_run_revisions', to=settings.AUTH_USER_MODEL)),
                ('source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_runs', to='liveclassroom.activitydefinitionrevision')),
            ],
            options={
                'ordering': ['activity', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='liveactivity',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_activities', to='liveclassroom.activityrunrevision'),
        ),
        migrations.CreateModel(
            name='FlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('kind', models.CharField(default='activity', max_length=32)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_steps', to='liveclassroom.activitydefinition')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='liveclassroom.flow')),
            ],
            options={
                'ordering': ['flow', 'position'],
            },
        ),
        migrations.CreateModel(
            name='SessionChannelState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('display', 'Classroom display'), ('participants', 'Participants')], max_length=16)),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('show_prompt', models.BooleanField(default=True)),
                ('show_aggregate', models.BooleanField(default=False)),
                ('show_answer', models.BooleanField(default=False)),
                ('show_explanation', models.BooleanField(default=False)),
                ('show_own_status', models.BooleanField(default=False)),
                ('allow_review', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_states', to='liveclassroom.liveactivity')),
                ('current_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_states', to='liveclassroom.activityrunrevision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_states', to='liveclassroom.livesession')),
            ],
            options={
                'ordering': ['session', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='SessionStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cohost', 'Co-host'), ('assistant', 'Assistant'), ('observer', 'Observer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='liveclassroom.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_staff_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['session', 'user'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('answer', models.JSONField(default=dict)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_revisions', to='liveclassroom.activityrunrevision')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='liveclassroom.submission')),
            ],
            options={
                'ordering': ['submission', 'revision'],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_submissions', to='liveclassroom.submissionrevision'),
        ),
        migrations.AddConstraint(
            model_name='activitydefinitionrevision',
            constraint=models.UniqueConstraint(fields=('definition', 'revision'), name='lc_definition_revision_once'),
        ),
        migrations.AddIndex(
            model_name='activitydefinition',
            index=models.Index(fields=['owner', 'type_key'], name='liveclassro_owner_i_1599fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='activityrunrevision',
            constraint=models.UniqueConstraint(fields=('activity', 'revision'), name='lc_activity_run_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(fields=('flow', 'position'), name='lc_flow_step_position'),
        ),
        migrations.AddConstraint(
            model_name='sessionchannelstate',
            constraint=models.UniqueConstraint(fields=('session', 'channel'), name='lc_session_channel_once'),
        ),
        migrations.AddConstraint(
            model_name='sessionstaff',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='lc_session_staff_once'),
        ),
        migrations.AddConstraint(
            model_name='submissionrevision',
            constraint=models.UniqueConstraint(fields=('submission', 'revision'), name='lc_submission_revision_once'),
        ),
    ]
