# Generated by Django 5.2 on 2026-09-04 05:40

import django.db.models.deletion
import liveclassroom.models.assets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionchannelstate',
            name='document_navigation',
            field=models.CharField(choices=[('follow', 'Follow teacher'), ('paged', 'Page controls'), ('scroll', 'Continuous scroll')], default='follow', max_length=16),
        ),
        migrations.AddField(
            model_name='sessionchannelstate',
            name='document_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ClassroomAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('server_path', 'Server path')], max_length=16)),
                ('content_file', models.FileField(blank=True, upload_to=liveclassroom.models.assets.asset_upload_path)),
                ('server_path', models.TextField(blank=True)),
                ('original_name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('pptx', 'PowerPoint'), ('video', 'Video')], max_length=16)),
                ('content_type', models.CharField(max_length=100)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='activitydefinition',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_definitions', to='liveclassroom.classroomasset'),
        ),
        migrations.AddField(
            model_name='activitydefinitionrevision',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_definition_revisions', to='liveclassroom.classroomasset'),
        ),
        migrations.AddField(
            model_name='activityrunrevision',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_run_revisions', to='liveclassroom.classroomasset'),
        ),
        migrations.AddIndex(
            model_name='classroomasset',
            index=models.Index(fields=['owner', 'created_at'], name='liveclassro_owner_i_d46cfc_idx'),
        ),
    ]
