# Generated by Django 6.0.3 on 2026-09-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("liveclassroom", "0002_public_demo_lessons"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.AddField(model_name="participant", name="is_test", field=models.BooleanField(default=False)),
        migrations.AddField(
            model_name="participant",
            name="test_owner",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="liveclassroom_test_participants", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(condition=models.Q(("is_test", True)), fields=("session", "test_owner"), name="lc_one_test_participant_per_owner_session"),
        ),
    ]
