# Generated by Django 6.0.3 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("liveclassroom", "0003_test_participants")]

    operations = [
        migrations.AddField(
            model_name="liveactivity",
            name="runtime_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
