# Generated by Django 6.0.3 on 2026-09-03 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0003_sessionmessage_commandreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionchannelstate',
            name='show_own_status',
            field=models.BooleanField(default=True),
        ),
    ]
