# Generated by Django 6.0.3 on 2026-09-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0005_teaching_course_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydefinition',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitydefinitionrevision',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
