# Generated by Django 6.0.3 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveclassroom", "0006_activity_question_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionBank",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="question_banks", to="liveclassroom.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveclassroom_question_banks", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at", "-id")},
        ),
        migrations.CreateModel(
            name="QuestionBankItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bank", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="liveclassroom.questionbank")),
                ("definition", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="question_bank_items", to="liveclassroom.activitydefinition")),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.AddIndex(model_name="questionbank", index=models.Index(fields=["owner", "updated_at"], name="liveclassro_owner_i_a86a91_idx")),
        migrations.AddConstraint(model_name="questionbankitem", constraint=models.UniqueConstraint(fields=("bank", "definition"), name="lc_question_bank_item_once")),
    ]
