# Generated by Django 6.0.3 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liveclassroom", "0007_question_banks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("theme", models.CharField(default="default", max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decks", to="liveclassroom.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveclassroom_decks", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at", "-id")},
        ),
        migrations.CreateModel(
            name="DeckSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("position", models.PositiveIntegerField()),
                ("markdown", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deck", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="slides", to="liveclassroom.deck")),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.CreateModel(
            name="DeckSlideAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deck_slide_links", to="liveclassroom.classroomasset")),
                ("slide", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="asset_links", to="liveclassroom.deckslide")),
            ],
        ),
        migrations.AddField(model_name="deckslide", name="assets", field=models.ManyToManyField(related_name="deck_slides", through="liveclassroom.DeckSlideAsset", to="liveclassroom.classroomasset")),
        migrations.AddIndex(model_name="deck", index=models.Index(fields=["owner", "updated_at"], name="liveclassro_owner_i_b0ce72_idx")),
        migrations.AddConstraint(model_name="deckslide", constraint=models.UniqueConstraint(fields=("deck", "key"), name="lc_deck_slide_key_once")),
        migrations.AddConstraint(model_name="deckslide", constraint=models.UniqueConstraint(fields=("deck", "position"), name="lc_deck_slide_position_once")),
        migrations.AddConstraint(model_name="deckslideasset", constraint=models.UniqueConstraint(fields=("slide", "asset"), name="lc_deck_slide_asset_once")),
    ]
