# Generated by Django 6.0.3 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("liveclassroom", "0008_native_decks")]

    operations = [
        migrations.CreateModel(
            name="DeckSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("theme", models.CharField(default="default", max_length=80)),
                ("public_manifest", models.JSONField(default=list)),
                ("private_notes", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_deck", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="snapshots", to="liveclassroom.deck")),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="DeckSnapshotAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deck_snapshot_links", to="liveclassroom.classroomasset")),
                ("snapshot", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="asset_links", to="liveclassroom.decksnapshot")),
            ],
        ),
        migrations.AddField(model_name="decksnapshot", name="assets", field=models.ManyToManyField(related_name="deck_snapshots", through="liveclassroom.DeckSnapshotAsset", to="liveclassroom.classroomasset")),
        migrations.AddConstraint(model_name="decksnapshotasset", constraint=models.UniqueConstraint(fields=("snapshot", "asset"), name="lc_deck_snapshot_asset_once")),
    ]
