# Generated by Django 6.0.3 on 2026-09-09 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0009_deck_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='liveclassroom.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('position', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=6, max_digits=16)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liveclassroom.assessmentdefinition')),
                ('question_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_items', to='liveclassroom.activitydefinitionrevision')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='assessmentdefinition',
            index=models.Index(fields=['owner', 'updated_at'], name='liveclassro_owner_i_cec8f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment', 'key'), name='lc_assessment_item_key_once'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment', 'position'), name='lc_assessment_item_position_once'),
        ),
    ]
