# Generated by Django 6.0.3 on 2026-09-10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0010_assessmentdefinition_assessmentitem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("source_version", models.PositiveIntegerField()),
                ("audience", models.CharField(choices=[("authenticated_link", "Authenticated link"), ("class", "Class")], max_length=32)),
                ("title", models.CharField(max_length=200)),
                ("manifest", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assessment_runs", to="liveclassroom.course")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="liveclassroom_assessment_runs", to=settings.AUTH_USER_MODEL)),
                ("source_assessment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_runs", to="liveclassroom.assessmentdefinition")),
            ],
            options={"ordering": ("-created_at", "-id")},
        ),
        migrations.CreateModel(
            name="AssessmentRunAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assessment_run_links", to="liveclassroom.classroomasset")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="asset_links", to="liveclassroom.assessmentrun")),
            ],
        ),
        migrations.AddField(model_name="assessmentrun", name="assets", field=models.ManyToManyField(related_name="assessment_runs", through="liveclassroom.AssessmentRunAsset", to="liveclassroom.classroomasset")),
        migrations.AddIndex(model_name="assessmentrun", index=models.Index(fields=["owner", "created_at"], name="liveclassro_owner_i_b6e114_idx")),
        migrations.AddIndex(model_name="assessmentrun", index=models.Index(fields=["public_id"], name="liveclassro_public__15942a_idx")),
        migrations.AddConstraint(model_name="assessmentrunasset", constraint=models.UniqueConstraint(fields=("run", "asset"), name="lc_assessment_run_asset_once")),
    ]
