# Generated by Django 5.2 on 2026-09-09 19:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0011_assessment_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('finalization_reason', models.CharField(blank=True, max_length=32)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='liveclassroom.assessmentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liveclassroom_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('run', 'user', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('position', models.PositiveIntegerField()),
                ('points', models.DecimalField(decimal_places=6, max_digits=16)),
                ('manifest', models.JSONField(default=dict)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='liveclassroom.assessmentattempt')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptStartReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_receipts', to='liveclassroom.assessmentattempt')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_receipts', to='liveclassroom.assessmentrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_attempt_start_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('run', 'user', 'attempt_number'), name='lc_attempt_number_once'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('run', 'user'), name='lc_one_active_attempt'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'key'), name='lc_attempt_item_key_once'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='lc_attempt_item_position_once'),
        ),
        migrations.AddConstraint(
            model_name='attemptstartreceipt',
            constraint=models.UniqueConstraint(fields=('run', 'user', 'request_id'), name='lc_attempt_start_receipt_once'),
        ),
    ]
