# Generated by Django 6.0.3 on 2026-09-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0011_participant_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authoringjob',
            name='lease_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='authoringjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='liveclassro_status_4bac7a_idx'),
        ),
    ]
