# Generated by Django 5.2 on 2026-09-09 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0012_assessment_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('answer', models.JSONField(default=dict)),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_answer_revisions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_revisions', to='liveclassroom.assessmentattemptitem')),
            ],
            options={
                'ordering': ('item', 'version'),
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_receipts', to='liveclassroom.assessmentattempt')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receipts', to='liveclassroom.answerrevision')),
            ],
        ),
        migrations.AddIndex(
            model_name='answerrevision',
            index=models.Index(fields=['item', 'version'], name='lc_answer_item_version_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerrevision',
            constraint=models.UniqueConstraint(fields=('item', 'version'), name='lc_answer_revision_once'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswerreceipt',
            constraint=models.UniqueConstraint(fields=('attempt', 'request_id'), name='lc_attempt_answer_receipt_once'),
        ),
    ]
