# Generated by Django 5.2 on 2026-09-10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_default_sections(apps, schema_editor):
    AssessmentDefinition = apps.get_model("liveclassroom", "AssessmentDefinition")
    AssessmentSection = apps.get_model("liveclassroom", "AssessmentSection")
    AssessmentSectionEntry = apps.get_model("liveclassroom", "AssessmentSectionEntry")
    for assessment in AssessmentDefinition.objects.all().iterator():
        section = AssessmentSection.objects.create(
            assessment_id=assessment.pk,
            key=uuid.uuid4(),
            title="Section 1",
            position=1,
        )
        items = assessment.items.order_by("position", "id").all()
        AssessmentSectionEntry.objects.bulk_create(
            [
                AssessmentSectionEntry(
                    section_id=section.pk,
                    key=uuid.uuid4(),
                    position=item.position,
                    kind="fixed",
                    item_id=item.pk,
                )
                for item in items
            ]
        )


def remove_backfilled_sections(apps, schema_editor):
    AssessmentSection = apps.get_model("liveclassroom", "AssessmentSection")
    AssessmentSection.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0013_attempt_answer_revisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentSection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=200)),
                ("position", models.PositiveIntegerField()),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="liveclassroom.assessmentdefinition",
                    ),
                ),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.CreateModel(
            name="AssessmentSectionEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("position", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("fixed", "Fixed question"), ("pool", "Question pool")], max_length=12
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("sample_size", models.PositiveIntegerField(blank=True, null=True)),
                ("points", models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ("shuffle_options", models.BooleanField(default=False)),
                (
                    "bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessment_pool_entries",
                        to="liveclassroom.questionbank",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_entries",
                        to="liveclassroom.assessmentitem",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="liveclassroom.assessmentsection",
                    ),
                ),
            ],
            options={"ordering": ("position", "id")},
        ),
        migrations.AddConstraint(
            model_name="assessmentsection",
            constraint=models.UniqueConstraint(fields=("assessment", "key"), name="lc_assessment_section_key_once"),
        ),
        migrations.AddConstraint(
            model_name="assessmentsection",
            constraint=models.UniqueConstraint(
                fields=("assessment", "position"), name="lc_assessment_section_position_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsectionentry",
            constraint=models.UniqueConstraint(fields=("section", "key"), name="lc_assessment_section_entry_key_once"),
        ),
        migrations.AddConstraint(
            model_name="assessmentsectionentry",
            constraint=models.UniqueConstraint(
                fields=("section", "position"), name="lc_assessment_section_entry_position_once"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsectionentry",
            constraint=models.UniqueConstraint(
                fields=("section", "item"), name="lc_assessment_section_fixed_item_once"
            ),
        ),
        migrations.RunPython(backfill_default_sections, remove_backfilled_sections),
    ]
