# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0014_assessment_sections"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentAttemptGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("graded", "Graded"), ("pending", "Pending")], default="pending", max_length=16)),
                ("possible_points", models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ("awarded_points", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("graded_count", models.PositiveIntegerField(default=0)),
                ("pending_count", models.PositiveIntegerField(default=0)),
                ("ungraded_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="grade", to="liveclassroom.assessmentattempt")),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentItemGrade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("graded", "Graded"), ("pending", "Pending"), ("ungraded", "Ungraded"), ("error", "Error")], max_length=16)),
                ("normalized_score", models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ("possible_points", models.DecimalField(decimal_places=6, max_digits=16)),
                ("awarded_points", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("retained_answer", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="automatic", max_length=32)),
                ("rule_version", models.CharField(default="activity-registry-v1", max_length=100)),
                ("diagnostic_code", models.CharField(blank=True, default="", max_length=64)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="grade", to="liveclassroom.assessmentattemptitem")),
            ],
        ),
        migrations.CreateModel(
            name="AssessmentGradeDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(max_length=16)),
                ("normalized_score", models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ("possible_points", models.DecimalField(decimal_places=6, max_digits=16)),
                ("awarded_points", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("retained_answer", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="automatic", max_length=32)),
                ("rule_version", models.CharField(default="activity-registry-v1", max_length=100)),
                ("diagnostic_code", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=timezone.now)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="liveclassroom_grade_decisions", to=settings.AUTH_USER_MODEL)),
                ("attempt", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grade_decisions", to="liveclassroom.assessmentattempt")),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grade_decisions", to="liveclassroom.assessmentattemptitem")),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddIndex(
            model_name="assessmentgradedecision",
            index=models.Index(fields=["attempt", "created_at"], name="lc_grade_decision_attempt_idx"),
        ),
        migrations.AddIndex(
            model_name="assessmentgradedecision",
            index=models.Index(fields=["item", "created_at"], name="lc_grade_decision_item_idx"),
        ),
    ]
