# Generated by Django 5.2 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0015_assessment_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentitemgrade",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentgradedecision",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
