# Generated by Django 6.0.3 on 2026-09-09 22:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0016_manual_grade_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResultRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('scores', 'Scores'), ('answers', 'Answers'), ('explanations', 'Explanations'), ('comments', 'Comments')], max_length=20)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_result_releases', to=settings.AUTH_USER_MODEL)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_releases', to='liveclassroom.assessmentattempt')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_releases', to='liveclassroom.assessmentrun')),
            ],
            options={
                'ordering': ('run', 'attempt', 'dimension', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('attempt__isnull', True)), fields=('run', 'dimension'), name='lc_result_release_run_once'), models.UniqueConstraint(condition=models.Q(('attempt__isnull', False)), fields=('run', 'attempt', 'dimension'), name='lc_result_release_attempt_once')],
            },
        ),
    ]
