# Generated by Django 5.2 on 2026-09-10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0017_assessmentresultrelease"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingRuleRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_key", models.UUIDField()),
                ("rule_version", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("configuration", models.JSONField()),
                ("reason", models.CharField(max_length=255)),
                ("approved_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liveclassroom_grading_rule_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_rule_revisions",
                        to="liveclassroom.assessmentrun",
                    ),
                ),
            ],
            options={
                "ordering": ("run", "item_key", "version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "item_key", "version"),
                        name="lc_grading_rule_revision_once",
                    ),
                ],
                "indexes": [
                    models.Index(
                        fields=("run", "item_key", "rule_version"),
                        name="lc_grading_rule_lookup_idx",
                    ),
                ],
            },
        ),
    ]
