# Generated by Django 6.0.3 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liveclassroom", "0018_grading_rule_revisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentsection",
            name="shuffle_questions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="current_item_position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="highest_accessible_item_position",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="locked_item_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="navigation_mode",
            field=models.CharField(default="free", max_length=20),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="navigation_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
