# Generated by Django 5.2 on 2026-09-10 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0019_exam_navigation_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('question', 'Question'), ('bank', 'Question bank'), ('deck', 'Deck'), ('assessment', 'Assessment')], max_length=16)),
                ('resource_id', models.PositiveBigIntegerField()),
                ('source_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_content_shares_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_content_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'kind', 'resource_id'], name='lc_content_share_read_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('owner', 'recipient', 'kind', 'resource_id'), name='lc_content_share_active_once'), models.CheckConstraint(condition=models.Q(('resource_id__gt', 0)), name='lc_content_share_resource_positive')],
            },
        ),
    ]
