# Generated by Django 5.2 on 2026-09-10 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclassroom', '0020_content_shares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authoringjob',
            name='artifact_type',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.CreateModel(
            name='AuthoringDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('question', 'Question'), ('deck', 'Deck'), ('assessment', 'Assessment')], max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('source_fingerprints', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='proposed', max_length=16)),
                ('accepted_object_type', models.CharField(blank=True, default='', max_length=24)),
                ('accepted_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=24)),
                ('target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('expected_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liveclassroom_accepted_authoring_drafts', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authoring_drafts', to='liveclassroom.authoringmessage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveclassroom_authoring_drafts', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='liveclassroom.authoringthread')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['owner', 'status', 'created_at'], name='liveclassro_owner_i_608dca_idx'), models.Index(fields=['thread', 'created_at'], name='liveclassro_thread__fa328a_idx')],
            },
        ),
        migrations.AlterField(
            model_name='authoringattachment',
            name='source_type',
            field=models.CharField(
                choices=[
                    ('activity', 'Activity'),
                    ('question_bank', 'Question bank'),
                    ('deck', 'Deck'),
                    ('assessment', 'Assessment'),
                    ('flow', 'Flow'),
                    ('flow_step', 'Flow step'),
                    ('provider', 'Content provider'),
                ],
                max_length=32,
            ),
        ),
    ]
