"""Authorized VaultPub fragment views for Markdown activity fields.

These views intentionally do not accept Markdown or filesystem paths from a
request.  A caller selects an immutable definition/run revision, checks the
actor and reveal state, and only then passes the selected field to the
optional VaultPub adapter.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from .integrations.vaultpub_documents import VaultPubUnavailable
from .integrations.vaultpub_fragments import render_fragment as render_vaultpub_fragment
from .models import (
    ActivityDefinitionRevision,
    ActivityRunRevision,
    LiveSession,
    Participant,
    SessionChannelState,
)
from .services.classroom import ClassroomError, can_view_session
from .services.permissions import can_use_activity_definition

FRAGMENT_FIELDS = frozenset({"prompt", "explanation", "feedback_correct", "feedback_incorrect"})


@require_http_methods(["GET", "HEAD"])
def render_fragment(request, *, revision, field: str, url_prefix: str) -> JsonResponse:
    """Render one already-authorized immutable revision field.

    ``revision`` is deliberately a model instance rather than a request value;
    URL wrappers must perform the exact definition/run authorization first.
    ``url_prefix`` must be reverse-generated by the wrapper and end with a
    slash.  The prefix is also used for any direct sibling assets registered by
    VaultPub.
    """
    markdown = fragment_markdown(revision, field)
    if markdown is None:
        raise Http404("Fragment not found")
    key = revision_key(revision)
    try:
        return render_vaultpub_fragment(
            request,
            markdown=markdown,
            url_prefix=url_prefix,
            revision_key=key,
        )
    except VaultPubUnavailable:
        return JsonResponse(
            {
                "detail": "Markdown fragment rendering is unavailable.",
                "code": "vaultpub_unavailable",
            },
            status=503,
        )


@require_http_methods(["GET", "HEAD"])
def definition_fragment(request, revision_id: int, field: str, *, url_prefix: str | None = None) -> JsonResponse:
    """Render a teacher-authorized draft definition revision."""
    revision = get_object_or_404(
        ActivityDefinitionRevision.objects.select_related("definition", "definition__course"),
        pk=revision_id,
    )
    if not can_use_activity_definition(request.user, revision.definition):
        raise Http404("Fragment not found")
    prefix = url_prefix or reverse(
        "liveclassroom:api-v1-definition-fragment",
        args=[revision_id, field],
    )
    return render_fragment(request, revision=revision, field=field, url_prefix=prefix)


@require_http_methods(["GET", "HEAD"])
def session_fragment(
    request,
    session_id: int,
    revision_id: int,
    field: str,
    *,
    url_prefix: str | None = None,
) -> JsonResponse:
    """Render an exact live revision after repeating its audience checks."""
    revision = get_object_or_404(
        ActivityRunRevision.objects.select_related("activity", "activity__session"),
        pk=revision_id,
        activity__session_id=session_id,
    )
    if not _can_read_session_fragment(request, revision, field):
        raise Http404("Fragment not found")
    prefix = url_prefix or reverse(
        "liveclassroom:api-v1-session-fragment",
        args=[session_id, revision_id, field],
    )
    return render_fragment(request, revision=revision, field=field, url_prefix=prefix)


def fragment_markdown(revision: ActivityDefinitionRevision | ActivityRunRevision, field: str) -> str | None:
    """Return only the whitelisted Markdown field from an immutable payload."""
    if field not in FRAGMENT_FIELDS:
        raise Http404("Fragment not found")
    snapshot = _snapshot(revision)
    content = snapshot.get("content") if isinstance(snapshot.get("content"), Mapping) else snapshot
    metadata = snapshot.get("metadata") if isinstance(snapshot.get("metadata"), Mapping) else {}
    if not isinstance(content, Mapping):
        content = {}

    direct_keys = {
        "prompt": ("prompt", "stem_markdown", "markdown"),
        "explanation": ("explanation_markdown", "explanation"),
        "feedback_correct": ("feedback_correct",),
        "feedback_incorrect": ("feedback_incorrect",),
    }[field]
    for key in direct_keys:
        value = content.get(key)
        if isinstance(value, str) and value.strip():
            return value
    for source in (metadata, content.get("metadata")):
        if not isinstance(source, Mapping):
            continue
        feedback = source.get("feedback")
        if isinstance(feedback, Mapping):
            value = feedback.get(field.removeprefix("feedback_"))
            if isinstance(value, str) and value.strip():
                return value
    return None


def revision_key(revision: ActivityDefinitionRevision | ActivityRunRevision) -> str:
    """Return a stable opaque cache key without exposing source paths."""
    if isinstance(revision, ActivityDefinitionRevision):
        return f"definition:{revision.definition_id}:r{revision.revision}"
    return f"run:{revision.activity_id}:r{revision.revision}"


def _snapshot(revision: ActivityDefinitionRevision | ActivityRunRevision) -> dict[str, Any]:
    if isinstance(revision, ActivityDefinitionRevision):
        payload = revision.payload
        metadata = revision.metadata
    else:
        payload = revision.definition_snapshot
        metadata = {}
    snapshot = dict(payload) if isinstance(payload, Mapping) else {}
    if "metadata" not in snapshot and isinstance(metadata, Mapping):
        snapshot["metadata"] = dict(metadata)
    return snapshot


def _can_read_session_fragment(request, revision: ActivityRunRevision, field: str) -> bool:
    if field not in FRAGMENT_FIELDS:
        return False
    activity = revision.activity
    session: LiveSession = activity.session
    try:
        # Staff retain the teacher-side authoring/review boundary.
        if can_view_session(request.user, session):
            return True
        from .api import _act_as_context, _participant_for_request

        acted_as, _active = _act_as_context(request, session)
        participant = acted_as or _participant_for_request(request, session)
    except (ClassroomError, AttributeError):
        return False
    if participant is None or participant.admission_state != Participant.AdmissionState.ADMITTED:
        return False
    state = SessionChannelState.objects.filter(
        session=session,
        channel=SessionChannelState.Channel.PARTICIPANTS,
    ).first()
    if state is None or state.current_activity_id != activity.id or state.current_revision_id != revision.id:
        return False

    # An ended session exposes only explicitly reviewable activity content.
    if session.status == LiveSession.Status.ENDED:
        if not activity.reviewable:
            return False
        visibility = activity.review_visibility if isinstance(activity.review_visibility, Mapping) else {}
        return field == "prompt" or visibility.get("show_explanation") is True
    if field == "prompt":
        return state.show_prompt is True
    return state.show_explanation is True
