from django.urls import path

from . import api, api_assets, api_authoring, api_flows, views

app_name = "liveclassroom"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("teacher/", views.TeacherDashboardView.as_view(), name="teacher-dashboard"),
    path("teacher/builder/", views.FlowBuilderView.as_view(), name="flow-builder"),
    path("teacher/flows/<int:flow_id>/builder/", views.FlowBuilderView.as_view(), name="flow-builder-detail"),
    path("teacher/sessions/<int:session_id>/", views.TeacherConsoleView.as_view(), name="teacher-console"),
    path("teacher/sessions/<int:session_id>/display/", views.ClassroomDisplayView.as_view(), name="classroom-display"),
    path("teacher/sessions/<int:session_id>/join-qr.svg", views.join_qr, name="join-qr"),

    path("join/", views.JoinView.as_view(), name="join"),
    path("sessions/<int:session_id>/", views.StudentSessionView.as_view(), name="student-session"),
    path("health/", views.health, name="health"),
    path("api/sessions/<int:session_id>/start/", api.start, name="api-start"),
    path("api/sessions/<int:session_id>/pause/", api.pause, name="api-pause"),
    path("api/sessions/<int:session_id>/end/", api.end, name="api-end"),
    path("api/sessions/<int:session_id>/archive/", api.archive, name="api-archive"),
    path("api/sessions/<int:session_id>/delete/", api.delete, name="api-delete"),
    path("api/sessions/<int:session_id>/activities/", api.launch, name="api-launch"),
    path("api/sessions/<int:session_id>/channels/publish/", api.publish_channel, name="api-publish-channel"),
    path("api/sessions/<int:session_id>/channels/settings/", api.channel_settings, name="api-channel-settings"),
    path("api/activities/<int:activity_id>/close/", api.transition, {"state": "closed"}, name="api-close"),
    path("api/activities/<int:activity_id>/reveal/", api.transition, {"state": "revealed"}, name="api-reveal"),
    path("api/activities/<int:activity_id>/revise/", api.revise, name="api-revise"),
    path("api/v1/sessions/<int:session_id>/state/", api.state, name="api-v1-state"),
    path("api/v1/activity-definitions/", api_authoring.activity_definitions, name="api-v1-activity-definitions"),
    path("api/v1/activity-types/", api_authoring.activity_types, name="api-v1-activity-types"),
    path("api/v1/activity-definitions/create/", api_authoring.create_activity, name="api-v1-activity-create"),
    path("api/v1/authoring/models/", api_authoring.authoring_models, name="api-v1-authoring-models"),
    path("api/v1/authoring/threads/", api_authoring.authoring_threads, name="api-v1-authoring-threads"),
    path(
        "api/v1/authoring/threads/<int:thread_id>/",
        api_authoring.authoring_thread,
        name="api-v1-authoring-thread",
    ),
    path(
        "api/v1/authoring/threads/<int:thread_id>/messages/",
        api_authoring.authoring_message,
        name="api-v1-authoring-message",
    ),
    path("api/v1/authoring/jobs/<int:job_id>/", api_authoring.authoring_job, name="api-v1-authoring-job"),
    path(
        "api/v1/activity-definitions/<int:activity_id>/revisions/",
        api_authoring.revise_activity_definition_api,
        name="api-v1-activity-revise",
    ),
    path("api/v1/sessions/<int:session_id>/start/", api.start, name="api-v1-start"),
    path("api/v1/sessions/<int:session_id>/pause/", api.pause, name="api-v1-pause"),
    path("api/v1/sessions/<int:session_id>/end/", api.end, name="api-v1-end"),
    path("api/v1/sessions/<int:session_id>/archive/", api.archive, name="api-v1-archive"),
    path("api/v1/sessions/<int:session_id>/delete/", api.delete, name="api-v1-delete"),
    path("api/v1/sessions/<int:session_id>/activities/", api.launch, name="api-v1-launch"),
    path("api/v1/sessions/<int:session_id>/channels/publish/", api.publish_channel, name="api-v1-publish-channel"),
    path("api/v1/sessions/<int:session_id>/channels/settings/", api.channel_settings, name="api-v1-channel-settings"),
    path("api/v1/sessions/<int:session_id>/files/", api_assets.session_file, name="api-v1-session-files"),
    path(
        "api/v1/sessions/<int:session_id>/presentation/",
        api_assets.presentation,
        name="api-v1-session-presentation",
    ),
    path(
        "api/v1/sessions/<int:session_id>/activity-revisions/<int:revision_id>/assets/<uuid:asset_id>/content/",
        api_assets.session_asset_content,
        name="api-v1-session-asset-content",
    ),
    path("api/v1/assets/<uuid:asset_id>/content/", api_assets.asset_content, name="api-v1-asset-content"),
    path("api/v1/sessions/<int:session_id>/join-account/", api.join_account, name="api-v1-join-account"),
    path(
        "api/v1/sessions/<int:session_id>/participants/<int:participant_id>/admission/",
        api.admission,
        name="api-v1-admission",
    ),
    path("api/v1/sessions/<int:session_id>/participants/", api.participants, name="api-v1-participants"),
    path("api/v1/sessions/<int:session_id>/staff/", api.staff, name="api-v1-staff"),
    path("api/v1/sessions/<int:session_id>/staff/assign/", api.staff_assign, name="api-v1-staff-assign"),
    path("api/v1/sessions/<int:session_id>/staff/<int:staff_id>/remove/", api.staff_remove, name="api-v1-staff-remove"),
    path("api/v1/sessions/<int:session_id>/history/", api.history, name="api-v1-history"),
    path("api/v1/sessions/<int:session_id>/analytics/", api.analytics, name="api-v1-analytics"),
    path("api/v1/sessions/<int:session_id>/export/", api.export_session, name="api-v1-export"),
    path("api/v1/sessions/<int:session_id>/chat/", api.chat_messages, name="api-v1-chat-messages"),
    path("api/v1/sessions/<int:session_id>/chat/send/", api.chat_send, name="api-v1-chat-send"),
    path("api/v1/sessions/<int:session_id>/chat/settings/", api.chat_settings, name="api-v1-chat-settings"),
    path("api/v1/sessions/join/<str:join_code>/", api.join, name="api-v1-join"),
    path("api/sessions/join/<str:join_code>/", api.join, name="api-join"),
    path("api/sessions/<int:session_id>/join-account/", api.join_account, name="api-join-account"),
    path(
        "api/sessions/<int:session_id>/participants/<int:participant_id>/admission/",
        api.admission,
        name="api-admission",
    ),
    path("api/sessions/<int:session_id>/participants/", api.participants, name="api-participants"),
    path("api/sessions/<int:session_id>/staff/", api.staff, name="api-staff"),
    path("api/sessions/<int:session_id>/staff/assign/", api.staff_assign, name="api-staff-assign"),
    path("api/sessions/<int:session_id>/staff/<int:staff_id>/remove/", api.staff_remove, name="api-staff-remove"),
    path("api/sessions/<int:session_id>/state/", api.state, name="api-state"),
    path("api/sessions/<int:session_id>/history/", api.history, name="api-history"),
    path("api/sessions/<int:session_id>/export/", api.export_session, name="api-export"),
    path("api/sessions/<int:session_id>/chat/", api.chat_messages, name="api-chat-messages"),
    path("api/sessions/<int:session_id>/chat/send/", api.chat_send, name="api-chat-send"),
    path("api/sessions/<int:session_id>/chat/settings/", api.chat_settings, name="api-chat-settings"),
    path("api/activities/<int:activity_id>/submissions/", api.submit, name="api-submit"),
    path("api/activities/<int:activity_id>/results/", api.results, name="api-results"),
    path("api/v1/activities/<int:activity_id>/close/", api.transition, {"state": "closed"}, name="api-v1-close"),
    path("api/v1/activities/<int:activity_id>/reveal/", api.transition, {"state": "revealed"}, name="api-v1-reveal"),
    path("api/v1/activities/<int:activity_id>/revise/", api.revise, name="api-v1-revise"),
    path("api/v1/activities/<int:activity_id>/submissions/", api.submit, name="api-v1-submit"),
    path("api/v1/activities/<int:activity_id>/results/", api.results, name="api-v1-results"),
    path("api/v1/flows/", api_flows.flows_collection, name="api-v1-flows"),
    path("api/v1/flows/import/", api_flows.import_flow_api, name="api-v1-flow-import"),
    path("api/v1/flows/<int:flow_id>/", api_flows.flow_detail, name="api-v1-flow-detail"),
    path("api/v1/flows/<int:flow_id>/duplicate/", api_flows.duplicate_flow_api, name="api-v1-flow-duplicate"),
    path("api/v1/flows/<int:flow_id>/steps/", api_flows.add_step_api, name="api-v1-flow-add-step"),
    path("api/v1/flows/<int:flow_id>/files/", api_assets.flow_file, name="api-v1-flow-files"),
    path("api/v1/flows/<int:flow_id>/steps/reorder/", api_flows.reorder_steps_api, name="api-v1-flow-reorder-steps"),
    path("api/v1/flows/<int:flow_id>/steps/<int:step_id>/", api_flows.delete_step_api, name="api-v1-flow-delete-step"),
    path(
        "api/v1/sessions/<int:session_id>/save-flow/",
        api_flows.save_session_flow_api,
        name="api-v1-session-save-flow",
    ),
]
