from django.urls import path

from . import (
    api,
    api_assessment_review,
    api_assessment_runs,
    api_assessments,
    api_assets,
    api_attempts,
    api_authoring,
    api_deck_portability,
    api_decks,
    api_flows,
    api_grading,
    api_organization,
    api_plans,
    api_presentation,
    api_progress,
    api_question_banks,
    api_release,
    api_review,
    deck_delivery,
    deck_views,
    document_views,
    fragment_views,
    views,
)

app_name = "liveclassroom"

urlpatterns = [
    path("api/v1/assessment-history/", api_assessment_review.history, name="api-v1-assessment-history"),
    path(
        "api/v1/assessment-runs/<uuid:public_id>/attempts/",
        api_attempts.start_attempt,
        name="api-v1-assessment-attempts",
    ),
    path("api/v1/attempts/<uuid:public_id>/", api_attempts.attempt_detail, name="api-v1-attempt-detail"),
    path(
        "api/v1/attempts/<uuid:public_id>/review/",
        api_assessment_review.review,
        name="api-v1-attempt-review",
    ),
    path(
        "api/v1/attempts/<uuid:public_id>/result/",
        api_release.result,
        name="api-v1-attempt-result",
    ),
    path(
        "api/v1/attempts/<uuid:public_id>/answers/",
        api_attempts.save_answer,
        name="api-v1-attempt-answers",
    ),
    path(
        "api/v1/attempts/<uuid:public_id>/submit/",
        api_attempts.submit,
        name="api-v1-attempt-submit",
    ),
    path("api/v1/grading/queue/", api_grading.grading_queue, name="api-v1-grading-queue"),
    path(
        "api/v1/attempts/<uuid:public_id>/items/<uuid:item_key>/manual-grade/",
        api_grading.manual_grade,
        name="api-v1-manual-grade",
    ),
    path(
        "api/v1/assessments/<int:assessment_id>/runs/",
        api_assessment_runs.assessment_runs,
        name="api-v1-assessment-runs",
    ),
    path(
        "api/v1/assessment-runs/<uuid:public_id>/",
        api_assessment_runs.assessment_run_detail,
        name="api-v1-assessment-run-detail",
    ),
    path(
        "api/v1/assessment-runs/<uuid:public_id>/available/",
        api_assessment_runs.available_assessment_run,
        name="api-v1-available-assessment-run",
    ),
    path(
        "api/v1/assessment-runs/<uuid:public_id>/release/",
        api_release.release,
        name="api-v1-assessment-run-release",
    ),
    path(
        "api/v1/assessment-runs/<uuid:public_id>/progress/",
        api_progress.run_progress,
        name="api-v1-assessment-run-progress",
    ),
    path(
        "api/v1/students/<int:user_id>/overview/",
        api_progress.student_overview,
        name="api-v1-student-overview",
    ),
    path("api/v1/assessments/", api_assessments.assessments, name="api-v1-assessments"),
    path(
        "api/v1/assessments/<int:assessment_id>/",
        api_assessments.assessment_detail,
        name="api-v1-assessment-detail",
    ),
    path(
        "api/v1/assessments/<int:assessment_id>/items/",
        api_assessments.assessment_items,
        name="api-v1-assessment-items",
    ),
    path(
        "api/v1/assessments/<int:assessment_id>/sections/",
        api_assessments.assessment_sections,
        name="api-v1-assessment-sections",
    ),
    path(
        "api/v1/assessments/<int:assessment_id>/copy/",
        api_assessments.assessment_copy,
        name="api-v1-assessment-copy",
    ),
    path(
        "api/v1/assessments/<int:assessment_id>/preset/",
        api_assessments.assessment_preset,
        name="api-v1-assessment-preset",
    ),
    path(
        "api/v1/activity-definitions/<int:revision_id>/fragments/<str:field>/",
        fragment_views.definition_fragment,
        name="api-v1-definition-fragment",
    ),
    path(
        "api/v1/sessions/<int:session_id>/activity-revisions/<int:revision_id>/fragments/<str:field>/",
        fragment_views.session_fragment,
        name="api-v1-session-fragment",
    ),
    path("api/v1/decks/", api_decks.decks, name="api-v1-decks"),
    path(
        "api/v1/decks/import/preview/",
        api_deck_portability.deck_import_preview,
        name="api-v1-deck-import-preview",
    ),
    path("api/v1/decks/import/", api_deck_portability.deck_import, name="api-v1-deck-import"),
    path(
        "api/v1/decks/<int:deck_id>/export/",
        api_deck_portability.deck_export,
        name="api-v1-deck-export",
    ),
    path("api/v1/decks/<int:deck_id>/", api_decks.deck_detail, name="api-v1-deck-detail"),
    path("api/v1/decks/<int:deck_id>/slides/", api_decks.deck_slides, name="api-v1-deck-slides"),
    path("api/v1/decks/<int:deck_id>/copy/", api_decks.deck_copy, name="api-v1-deck-copy"),
    path(
        "api/v1/decks/<int:deck_id>/snapshots/",
        api_decks.deck_snapshots,
        name="api-v1-deck-snapshots",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/present/",
        api_decks.session_deck_present,
        name="api-v1-session-deck-present",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/<int:snapshot_id>/",
        deck_delivery.snapshot_payload,
        name="api-v1-session-deck-payload",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/<int:snapshot_id>/__notes__/",
        deck_delivery.snapshot_notes,
        name="api-v1-session-deck-notes",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/<int:snapshot_id>/__slides__/",
        deck_delivery.snapshot_slides,
        name="api-v1-session-deck-slides",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/<int:snapshot_id>/__api__/slides/",
        deck_delivery.snapshot_slides_payload,
        name="api-v1-session-deck-slides-payload",
    ),
    path(
        "api/v1/sessions/<int:session_id>/decks/<int:snapshot_id>/__assets__/<path:resource_path>",
        deck_delivery.snapshot_resource,
        name="api-v1-session-deck-resource",
    ),
    path("api/v1/question-banks/", api_question_banks.question_banks, name="api-v1-question-banks"),
    path(
        "api/v1/question-banks/<int:bank_id>/",
        api_question_banks.question_bank_detail,
        name="api-v1-question-bank-detail",
    ),
    path(
        "api/v1/question-banks/<int:bank_id>/questions/",
        api_question_banks.question_bank_questions,
        name="api-v1-question-bank-questions",
    ),
    path(
        "api/v1/question-banks/<int:bank_id>/questions/<int:definition_id>/",
        api_question_banks.question_bank_question,
        name="api-v1-question-bank-question",
    ),
    path(
        "api/v1/question-banks/<int:bank_id>/questions/<int:definition_id>/copy/",
        api_question_banks.question_bank_question_copy,
        name="api-v1-question-bank-question-copy",
    ),
    path(
        "api/v1/documents/<uuid:asset_id>/",
        document_views.document_note,
        name="api-v1-document-root",
    ),
    path(
        "api/v1/documents/<uuid:asset_id>/__slides__/<path:note_path>",
        document_views.document_slides,
        name="api-v1-document-slides",
    ),
    path(
        "api/v1/documents/<uuid:asset_id>/__api__/slides/<path:note_path>",
        document_views.document_slides_payload,
        name="api-v1-document-slides-payload",
    ),
    path(
        "api/v1/documents/<uuid:asset_id>/__assets__/<path:resource_path>",
        document_views.document_resource,
        name="api-v1-document-resource",
    ),
    path(
        "api/v1/documents/<uuid:asset_id>/<path:note_path>",
        document_views.document_note,
        name="api-v1-document-note",
    ),
    path(
        "api/v1/session-documents/<int:session_id>/<int:revision_id>/<uuid:asset_id>/",
        document_views.session_document_note,
        name="api-v1-session-document-root",
    ),
    path(
        "api/v1/session-documents/<int:session_id>/<int:revision_id>/<uuid:asset_id>/__slides__/<path:note_path>",
        document_views.session_document_slides,
        name="api-v1-session-document-slides",
    ),
    path(
        "api/v1/session-documents/<int:session_id>/<int:revision_id>/<uuid:asset_id>/__api__/slides/<path:note_path>",
        document_views.session_document_slides_payload,
        name="api-v1-session-document-slides-payload",
    ),
    path(
        "api/v1/session-documents/<int:session_id>/<int:revision_id>/<uuid:asset_id>/__assets__/<path:resource_path>",
        document_views.session_document_resource,
        name="api-v1-session-document-resource",
    ),
    path(
        "api/v1/session-documents/<int:session_id>/<int:revision_id>/<uuid:asset_id>/<path:note_path>",
        document_views.session_document_note,
        name="api-v1-session-document-note",
    ),
    path(
        "api/v1/teaching-courses/",
        api_organization.teaching_courses,
        name="api-v1-teaching-courses",
    ),
    path(
        "api/v1/teaching-courses/<int:teaching_course_id>/",
        api_organization.teaching_course_detail,
        name="api-v1-teaching-course-detail",
    ),
    path(
        "api/v1/teaching-courses/<int:teaching_course_id>/classes/",
        api_organization.teaching_course_classes,
        name="api-v1-teaching-course-classes",
    ),
    path(
        "api/v1/teaching-courses/<int:teaching_course_id>/classes/<int:class_id>/",
        api_organization.teaching_course_class,
        name="api-v1-teaching-course-class",
    ),
    path("api/v1/activities/<int:activity_id>/review/", api_review.review_settings, name="api-v1-review-settings"),
    path(
        "api/v1/flows/<int:flow_id>/steps/<int:step_id>/edit/", api_plans.lesson_step_edit, name="api-v1-flow-step-edit"
    ),
    path("api/v1/workspace/", api_plans.workspace, name="api-v1-workspace"),
    path("api/v1/courses/", api_plans.courses, name="api-v1-courses"),
    path("api/v1/courses/<int:course_id>/", api_plans.course_detail, name="api-v1-course-detail"),
    path("api/v1/courses/<int:course_id>/members/", api_plans.course_members, name="api-v1-course-members"),
    path("api/v1/courses/<int:course_id>/lessons/", api_plans.associate_lesson, name="api-v1-course-lessons"),
    path("api/v1/flows/<int:flow_id>/shares/", api_plans.shares, name="api-v1-flow-shares"),
    path("api/v1/sessions/", api_plans.sessions_create, name="api-v1-session-create"),
    path("api/v1/sessions/<int:session_id>/plan/", api_plans.session_plan, name="api-v1-session-plan"),
    path("api/v1/sessions/<int:session_id>/plan/reorder/", api_plans.plan_reorder, name="api-v1-plan-reorder"),
    path("api/v1/sessions/<int:session_id>/plan/compare/", api_plans.plan_comparison, name="api-v1-plan-compare"),
    path("api/v1/sessions/<int:session_id>/plan/<int:step_id>/", api_plans.plan_step, name="api-v1-plan-step"),
    path(
        "api/v1/sessions/<int:session_id>/plan/<int:step_id>/launch/", api_plans.plan_launch, name="api-v1-plan-launch"
    ),
    path("", views.HomeView.as_view(), name="home"),
    path("help/", views.HelpView.as_view(), name="help"),
    path("teacher/", views.TeacherDashboardView.as_view(), name="teacher-dashboard"),
    path("teacher/builder/", views.FlowBuilderView.as_view(), name="flow-builder"),
    path("teacher/decks/", views.DeckWorkspaceView.as_view(), name="deck-workspace"),
    path("teacher/assessments/", views.AssessmentWorkspaceView.as_view(), name="assessment-workspace"),
    path(
        "assessments/runs/<uuid:public_id>/",
        views.AssessmentAttemptView.as_view(),
        name="assessment-attempt",
    ),
    path("teacher/decks/<int:deck_id>/preview/", deck_views.preview, name="deck-preview"),
    path("teacher/flows/<int:flow_id>/builder/", views.FlowBuilderView.as_view(), name="flow-builder-detail"),
    path("teacher/sessions/<int:session_id>/", views.TeacherConsoleView.as_view(), name="teacher-console"),
    path("teacher/sessions/<int:session_id>/student-view/", views.StudentView.as_view(), name="student-view"),
    path("teacher/sessions/<int:session_id>/display/", views.ClassroomDisplayView.as_view(), name="classroom-display"),
    path("teacher/sessions/<int:session_id>/join-qr.svg", views.join_qr, name="join-qr"),
    path("join/", views.JoinView.as_view(), name="join"),
    path("sessions/<int:session_id>/", views.StudentSessionView.as_view(), name="student-session"),
    path("health/", views.health, name="health"),
    path("api/v1/sessions/<int:session_id>/state/", api.state, name="api-v1-state"),
    path("api/v1/activity-definitions/", api_authoring.activity_definitions, name="api-v1-activity-definitions"),
    path("api/v1/activity-types/", api_authoring.activity_types, name="api-v1-activity-types"),
    path("api/v1/activity-definitions/create/", api_authoring.create_activity, name="api-v1-activity-create"),
    path("api/v1/authoring/models/", api_authoring.authoring_models, name="api-v1-authoring-models"),
    path("api/v1/authoring/threads/", api_authoring.authoring_threads, name="api-v1-authoring-threads"),
    path(
        "api/v1/authoring/threads/<int:thread_id>/",
        api_authoring.authoring_thread,
        name="api-v1-authoring-thread",
    ),
    path(
        "api/v1/authoring/threads/<int:thread_id>/messages/",
        api_authoring.authoring_message,
        name="api-v1-authoring-message",
    ),
    path("api/v1/authoring/jobs/<int:job_id>/", api_authoring.authoring_job, name="api-v1-authoring-job"),
    path(
        "api/v1/activity-definitions/<int:activity_id>/revisions/",
        api_authoring.revise_activity_definition_api,
        name="api-v1-activity-revise",
    ),
    path("api/v1/sessions/<int:session_id>/start/", api.start, name="api-v1-start"),
    path("api/v1/sessions/<int:session_id>/pause/", api.pause, name="api-v1-pause"),
    path("api/v1/sessions/<int:session_id>/end/", api.end, name="api-v1-end"),
    path("api/v1/sessions/<int:session_id>/archive/", api.archive, name="api-v1-archive"),
    path("api/v1/sessions/<int:session_id>/delete/", api.delete, name="api-v1-delete"),
    path("api/v1/sessions/<int:session_id>/activities/", api.launch, name="api-v1-launch"),
    path("api/v1/sessions/<int:session_id>/channels/publish/", api.publish_channel, name="api-v1-publish-channel"),
    path("api/v1/sessions/<int:session_id>/channels/settings/", api.channel_settings, name="api-v1-channel-settings"),
    path("api/v1/sessions/<int:session_id>/files/", api_assets.session_file, name="api-v1-session-files"),
    path(
        "api/v1/sessions/<int:session_id>/presentation/",
        api_assets.presentation,
        name="api-v1-session-presentation",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/providers/",
        api_presentation.providers,
        name="api-v1-presentation-providers",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/providers/<str:provider>/search/",
        api_presentation.provider_search_api,
        name="api-v1-presentation-provider-search",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/providers/resolve/",
        api_presentation.provider_resolve,
        name="api-v1-presentation-provider-resolve",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/cues/",
        api_presentation.cues,
        name="api-v1-presentation-cues",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/cues/<uuid:cue_id>/",
        api_presentation.cue_detail,
        name="api-v1-presentation-cue-detail",
    ),
    path(
        "api/v1/sessions/<int:session_id>/presentation/cues/<uuid:cue_id>/launch/",
        api_presentation.cue_launch,
        name="api-v1-presentation-cue-launch",
    ),
    path(
        "api/v1/sessions/<int:session_id>/activity-revisions/<int:revision_id>/assets/<uuid:asset_id>/content/",
        api_assets.session_asset_content,
        name="api-v1-session-asset-content",
    ),
    path("api/v1/assets/", api_assets.assets, name="api-v1-assets"),
    path("api/v1/assets/<uuid:asset_id>/content/", api_assets.asset_content, name="api-v1-asset-content"),
    path("api/v1/sessions/<int:session_id>/join-account/", api.join_account, name="api-v1-join-account"),
    path(
        "api/v1/sessions/<int:session_id>/participants/<int:participant_id>/admission/",
        api.admission,
        name="api-v1-admission",
    ),
    path("api/v1/sessions/<int:session_id>/participants/", api.participants, name="api-v1-participants"),
    path("api/v1/sessions/<int:session_id>/student-view/test-student/", api.test_student, name="api-v1-test-student"),
    path(
        "api/v1/sessions/<int:session_id>/student-view/test-student/renew/",
        api.renew_test_student,
        name="api-v1-renew-test-student",
    ),
    path(
        "api/v1/sessions/<int:session_id>/student-view/activate/",
        api.activate_student_view,
        name="api-v1-student-view-activate",
    ),
    path("api/v1/sessions/<int:session_id>/staff/", api.staff, name="api-v1-staff"),
    path("api/v1/sessions/<int:session_id>/staff/assign/", api.staff_assign, name="api-v1-staff-assign"),
    path("api/v1/sessions/<int:session_id>/staff/<int:staff_id>/remove/", api.staff_remove, name="api-v1-staff-remove"),
    path("api/v1/sessions/<int:session_id>/history/", api_review.history, name="api-v1-history"),
    path("api/v1/sessions/<int:session_id>/analytics/", api.analytics, name="api-v1-analytics"),
    path("api/v1/sessions/<int:session_id>/export/", api.export_session, name="api-v1-export"),
    path("api/v1/sessions/<int:session_id>/chat/", api.chat_messages, name="api-v1-chat-messages"),
    path("api/v1/sessions/<int:session_id>/chat/send/", api.chat_send, name="api-v1-chat-send"),
    path("api/v1/sessions/<int:session_id>/chat/settings/", api.chat_settings, name="api-v1-chat-settings"),
    path("api/v1/sessions/join/<str:join_code>/", api.join, name="api-v1-join"),
    path("api/v1/activities/<int:activity_id>/close/", api.transition, {"state": "closed"}, name="api-v1-close"),
    path("api/v1/activities/<int:activity_id>/reveal/", api.transition, {"state": "revealed"}, name="api-v1-reveal"),
    path(
        "api/v1/activities/<int:activity_id>/close-and-show-answer/",
        api.close_and_show_answer,
        name="api-v1-close-and-show-answer",
    ),
    path("api/v1/activities/<int:activity_id>/timer/", api.timer, name="api-v1-timer"),
    path("api/v1/activities/<int:activity_id>/revise/", api.revise, name="api-v1-revise"),
    path("api/v1/activities/<int:activity_id>/submissions/", api.submit, name="api-v1-submit"),
    path("api/v1/activities/<int:activity_id>/results/", api.results, name="api-v1-results"),
    path("api/v1/flows/", api_flows.flows_collection, name="api-v1-flows"),
    path("api/v1/flows/import/", api_flows.import_flow_api, name="api-v1-flow-import"),
    path("api/v1/flows/<int:flow_id>/", api_flows.flow_detail, name="api-v1-flow-detail"),
    path("api/v1/flows/<int:flow_id>/duplicate/", api_flows.duplicate_flow_api, name="api-v1-flow-duplicate"),
    path("api/v1/flows/<int:flow_id>/steps/", api_flows.add_step_api, name="api-v1-flow-add-step"),
    path("api/v1/flows/<int:flow_id>/files/", api_assets.flow_file, name="api-v1-flow-files"),
    path("api/v1/flows/<int:flow_id>/steps/reorder/", api_flows.reorder_steps_api, name="api-v1-flow-reorder-steps"),
    path("api/v1/flows/<int:flow_id>/steps/<int:step_id>/", api_flows.delete_step_api, name="api-v1-flow-delete-step"),
    path(
        "api/v1/sessions/<int:session_id>/save-flow/",
        api_flows.save_session_flow_api,
        name="api-v1-session-save-flow",
    ),
]
