from django.urls import path

from . import api, views

app_name = "liveclassroom"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("teacher/", views.TeacherDashboardView.as_view(), name="teacher-dashboard"),
    path("teacher/sessions/<int:session_id>/", views.TeacherConsoleView.as_view(), name="teacher-console"),
    path("teacher/sessions/<int:session_id>/display/", views.ClassroomDisplayView.as_view(), name="classroom-display"),
    path("join/", views.JoinView.as_view(), name="join"),
    path("sessions/<int:session_id>/", views.StudentSessionView.as_view(), name="student-session"),
    path("health/", views.health, name="health"),
    path("api/sessions/<int:session_id>/start/", api.start, name="api-start"),
    path("api/sessions/<int:session_id>/pause/", api.pause, name="api-pause"),
    path("api/sessions/<int:session_id>/end/", api.end, name="api-end"),
    path("api/sessions/<int:session_id>/activities/", api.launch, name="api-launch"),
    path("api/sessions/<int:session_id>/channels/publish/", api.publish_channel, name="api-publish-channel"),
    path("api/sessions/<int:session_id>/channels/settings/", api.channel_settings, name="api-channel-settings"),
    path("api/activities/<int:activity_id>/close/", api.transition, {"state": "closed"}, name="api-close"),
    path("api/activities/<int:activity_id>/reveal/", api.transition, {"state": "revealed"}, name="api-reveal"),
    path("api/activities/<int:activity_id>/revise/", api.revise, name="api-revise"),
    path("api/v1/sessions/<int:session_id>/state/", api.state, name="api-v1-state"),
    path("api/v1/activity-definitions/", api.activity_definitions, name="api-v1-activity-definitions"),
    path("api/v1/activity-types/", api.activity_types, name="api-v1-activity-types"),
    path("api/v1/activity-definitions/create/", api.create_activity, name="api-v1-activity-create"),
    path(
        "api/v1/activity-definitions/<int:activity_id>/revisions/",
        api.revise_activity_definition_api,
        name="api-v1-activity-revise",
    ),
    path("api/v1/sessions/<int:session_id>/start/", api.start, name="api-v1-start"),
    path("api/v1/sessions/<int:session_id>/pause/", api.pause, name="api-v1-pause"),
    path("api/v1/sessions/<int:session_id>/end/", api.end, name="api-v1-end"),
    path("api/v1/sessions/<int:session_id>/activities/", api.launch, name="api-v1-launch"),
    path("api/v1/sessions/<int:session_id>/channels/publish/", api.publish_channel, name="api-v1-publish-channel"),
    path("api/v1/sessions/<int:session_id>/channels/settings/", api.channel_settings, name="api-v1-channel-settings"),
    path("api/v1/sessions/<int:session_id>/join-account/", api.join_account, name="api-v1-join-account"),
    path(
        "api/v1/sessions/<int:session_id>/participants/<int:participant_id>/admission/",
        api.admission,
        name="api-v1-admission",
    ),
    path("api/v1/sessions/<int:session_id>/participants/", api.participants, name="api-v1-participants"),
    path("api/v1/sessions/<int:session_id>/history/", api.history, name="api-v1-history"),
    path("api/v1/sessions/<int:session_id>/analytics/", api.analytics, name="api-v1-analytics"),
    path("api/v1/sessions/<int:session_id>/export/", api.export_session, name="api-v1-export"),
    path("api/v1/sessions/<int:session_id>/chat/", api.chat_messages, name="api-v1-chat-messages"),
    path("api/v1/sessions/<int:session_id>/chat/send/", api.chat_send, name="api-v1-chat-send"),
    path("api/v1/sessions/join/<str:join_code>/", api.join, name="api-v1-join"),
    path("api/sessions/join/<str:join_code>/", api.join, name="api-join"),
    path("api/sessions/<int:session_id>/join-account/", api.join_account, name="api-join-account"),
    path(
        "api/sessions/<int:session_id>/participants/<int:participant_id>/admission/",
        api.admission,
        name="api-admission",
    ),
    path("api/sessions/<int:session_id>/participants/", api.participants, name="api-participants"),
    path("api/sessions/<int:session_id>/state/", api.state, name="api-state"),
    path("api/sessions/<int:session_id>/history/", api.history, name="api-history"),
    path("api/sessions/<int:session_id>/export/", api.export_session, name="api-export"),
    path("api/sessions/<int:session_id>/chat/", api.chat_messages, name="api-chat-messages"),
    path("api/sessions/<int:session_id>/chat/send/", api.chat_send, name="api-chat-send"),
    path("api/activities/<int:activity_id>/submissions/", api.submit, name="api-submit"),
    path("api/activities/<int:activity_id>/results/", api.results, name="api-results"),
    path("api/v1/activities/<int:activity_id>/close/", api.transition, {"state": "closed"}, name="api-v1-close"),
    path("api/v1/activities/<int:activity_id>/reveal/", api.transition, {"state": "revealed"}, name="api-v1-reveal"),
    path("api/v1/activities/<int:activity_id>/revise/", api.revise, name="api-v1-revise"),
    path("api/v1/activities/<int:activity_id>/submissions/", api.submit, name="api-v1-submit"),
    path("api/v1/activities/<int:activity_id>/results/", api.results, name="api-v1-results"),
]
